grafana:
  adminPassword: admin123

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    retention: 7d

alertmanager:
  enabled: true