apiVersion: v1
kind: Secret
metadata:
  name: uit-dkhp-secret
  namespace: default
type: Opaque
stringData:
  # TODO: Thay thế YOUR_DB_HOST bằng fqdn của database từ Terraform, và YOUR_DB_PASSWORD bằng mật khẩu thực tế
  DATABASE_URL: "postgresql://pgadmin:YOUR_DB_PASSWORD@YOUR_DB_HOST:5432/uit_dkhp"
  JWT_SECRET: "change-me-in-production"
  JWT_EXPIRES_IN: "7d"
  MAILTRAP_USER: "your-mailtrap-user"
  MAILTRAP_PASS: "your-mailtrap-pass"
